server:
  port: 8001
eureka:
  instance:
    hostname: localhost   #指定Eureka主机
  client:
    register-with-eureka: false    #指定当前主机是否需要向注册中心注册(不用,因为当前主机就是Server，不是Client)
    fetch-registry: false          #指定当前主机是否需要获取注册信息(不用,因为当前主机就是Server，不是Client)
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
      #defaultZone: http://127.0.0.1:8000/eureka
